export const themes = [
  // ─── DARK THEMES ───────────────────────────────────────────────
  {
    id: "midnight",
    name: "Midnight",
    category: "dark",
    preview: ["#0f0f1a", "#1a1a2e", "#7c6af7"],
    vars: {
      "--bg-base":        "#0f0f1a",
      "--bg-surface":     "#1a1a2e",
      "--bg-elevated":    "#16213e",
      "--bg-input":       "#0d0d1f",
      "--border":         "#2a2a4a",
      "--text-primary":   "#e8e8ff",
      "--text-secondary": "#8888bb",
      "--text-muted":     "#555577",
      "--accent":         "#7c6af7",
      "--accent-hover":   "#6a58e5",
      "--accent-subtle":  "#1e1a3f",
      "--bubble-out":     "#7c6af7",
      "--bubble-out-text":"#ffffff",
      "--bubble-in":      "#1e1e35",
      "--bubble-in-text": "#e8e8ff",
      "--online":         "#22d3a5",
      "--scrollbar":      "#2a2a4a",
    },
  },
  {
    id: "obsidian",
    name: "Obsidian",
    category: "dark",
    preview: ["#0a0a0a", "#141414", "#ff6b6b"],
    vars: {
      "--bg-base":        "#0a0a0a",
      "--bg-surface":     "#141414",
      "--bg-elevated":    "#1c1c1c",
      "--bg-input":       "#0d0d0d",
      "--border":         "#2a2a2a",
      "--text-primary":   "#f0f0f0",
      "--text-secondary": "#888888",
      "--text-muted":     "#444444",
      "--accent":         "#ff6b6b",
      "--accent-hover":   "#ff5252",
      "--accent-subtle":  "#2a1515",
      "--bubble-out":     "#ff6b6b",
      "--bubble-out-text":"#ffffff",
      "--bubble-in":      "#1e1e1e",
      "--bubble-in-text": "#f0f0f0",
      "--online":         "#51fa7b",
      "--scrollbar":      "#2a2a2a",
    },
  },
  {
    id: "slate",
    name: "Slate",
    category: "dark",
    preview: ["#0d1117", "#161b22", "#58a6ff"],
    vars: {
      "--bg-base":        "#0d1117",
      "--bg-surface":     "#161b22",
      "--bg-elevated":    "#21262d",
      "--bg-input":       "#0d1117",
      "--border":         "#30363d",
      "--text-primary":   "#c9d1d9",
      "--text-secondary": "#8b949e",
      "--text-muted":     "#484f58",
      "--accent":         "#58a6ff",
      "--accent-hover":   "#388bfd",
      "--accent-subtle":  "#0d1f33",
      "--bubble-out":     "#1f6feb",
      "--bubble-out-text":"#ffffff",
      "--bubble-in":      "#21262d",
      "--bubble-in-text": "#c9d1d9",
      "--online":         "#3fb950",
      "--scrollbar":      "#30363d",
    },
  },
  {
    id: "amoled",
    name: "AMOLED",
    category: "dark",
    preview: ["#000000", "#0a0a0a", "#00e5ff"],
    vars: {
      "--bg-base":        "#000000",
      "--bg-surface":     "#0a0a0a",
      "--bg-elevated":    "#111111",
      "--bg-input":       "#050505",
      "--border":         "#1a1a1a",
      "--text-primary":   "#ffffff",
      "--text-secondary": "#777777",
      "--text-muted":     "#333333",
      "--accent":         "#00e5ff",
      "--accent-hover":   "#00b8d4",
      "--accent-subtle":  "#001f24",
      "--bubble-out":     "#00b8d4",
      "--bubble-out-text":"#000000",
      "--bubble-in":      "#141414",
      "--bubble-in-text": "#ffffff",
      "--online":         "#00e676",
      "--scrollbar":      "#1a1a1a",
    },
  },
  {
    id: "forest-night",
    name: "Forest Night",
    category: "dark",
    preview: ["#0d1f0d", "#132213", "#4ade80"],
    vars: {
      "--bg-base":        "#0d1f0d",
      "--bg-surface":     "#132213",
      "--bg-elevated":    "#1a2e1a",
      "--bg-input":       "#0a1a0a",
      "--border":         "#2a3f2a",
      "--text-primary":   "#d4f0d4",
      "--text-secondary": "#7ab87a",
      "--text-muted":     "#3a5a3a",
      "--accent":         "#4ade80",
      "--accent-hover":   "#22c55e",
      "--accent-subtle":  "#0f2d0f",
      "--bubble-out":     "#22c55e",
      "--bubble-out-text":"#fff",
      "--bubble-in":      "#1c2e1c",
      "--bubble-in-text": "#d4f0d4",
      "--online":         "#86efac",
      "--scrollbar":      "#2a3f2a",
    },
  },
  {
    id: "deep-ocean",
    name: "Deep Ocean",
    category: "dark",
    preview: ["#020b18", "#051525", "#0ea5e9"],
    vars: {
      "--bg-base":        "#020b18",
      "--bg-surface":     "#051525",
      "--bg-elevated":    "#082035",
      "--bg-input":       "#020e1e",
      "--border":         "#0e2d4a",
      "--text-primary":   "#bae6fd",
      "--text-secondary": "#5a9ec0",
      "--text-muted":     "#1e4060",
      "--accent":         "#0ea5e9",
      "--accent-hover":   "#0284c7",
      "--accent-subtle":  "#082030",
      "--bubble-out":     "#0284c7",
      "--bubble-out-text":"#fff",
      "--bubble-in":      "#0a1e30",
      "--bubble-in-text": "#bae6fd",
      "--online":         "#22d3ee",
      "--scrollbar":      "#0e2d4a",
    },
  },
  {
    id: "volcanic",
    name: "Volcanic",
    category: "dark",
    preview: ["#1a0a00", "#2d1200", "#f97316"],
    vars: {
      "--bg-base":        "#1a0a00",
      "--bg-surface":     "#2d1200",
      "--bg-elevated":    "#3d1800",
      "--bg-input":       "#150800",
      "--border":         "#4a2200",
      "--text-primary":   "#fde8cc",
      "--text-secondary": "#c07a40",
      "--text-muted":     "#5a3010",
      "--accent":         "#f97316",
      "--accent-hover":   "#ea6c0a",
      "--accent-subtle":  "#2d1500",
      "--bubble-out":     "#f97316",
      "--bubble-out-text":"#fff",
      "--bubble-in":      "#3a1800",
      "--bubble-in-text": "#fde8cc",
      "--online":         "#fbbf24",
      "--scrollbar":      "#4a2200",
    },
  },
  {
    id: "grape",
    name: "Grape",
    category: "dark",
    preview: ["#130920", "#1e0f30", "#c084fc"],
    vars: {
      "--bg-base":        "#130920",
      "--bg-surface":     "#1e0f30",
      "--bg-elevated":    "#2a1540",
      "--bg-input":       "#0f0718",
      "--border":         "#3a1f55",
      "--text-primary":   "#f0d8ff",
      "--text-secondary": "#a070c0",
      "--text-muted":     "#502a70",
      "--accent":         "#c084fc",
      "--accent-hover":   "#a855f7",
      "--accent-subtle":  "#2a0f40",
      "--bubble-out":     "#a855f7",
      "--bubble-out-text":"#fff",
      "--bubble-in":      "#261040",
      "--bubble-in-text": "#f0d8ff",
      "--online":         "#e879f9",
      "--scrollbar":      "#3a1f55",
    },
  },

  // ─── LIGHT THEMES ──────────────────────────────────────────────
  {
    id: "clean",
    name: "Clean",
    category: "light",
    preview: ["#ffffff", "#f5f5f5", "#3b82f6"],
    vars: {
      "--bg-base":        "#f0f2f5",
      "--bg-surface":     "#ffffff",
      "--bg-elevated":    "#f8f9fa",
      "--bg-input":       "#f0f2f5",
      "--border":         "#e0e0e0",
      "--text-primary":   "#111111",
      "--text-secondary": "#555555",
      "--text-muted":     "#999999",
      "--accent":         "#3b82f6",
      "--accent-hover":   "#2563eb",
      "--accent-subtle":  "#eff6ff",
      "--bubble-out":     "#3b82f6",
      "--bubble-out-text":"#fff",
      "--bubble-in":      "#f0f2f5",
      "--bubble-in-text": "#111111",
      "--online":         "#22c55e",
      "--scrollbar":      "#d0d0d0",
    },
  },
  {
    id: "paper",
    name: "Paper",
    category: "light",
    preview: ["#f5f0e8", "#fffdf7", "#8b5cf6"],
    vars: {
      "--bg-base":        "#f5f0e8",
      "--bg-surface":     "#fffdf7",
      "--bg-elevated":    "#fff8ec",
      "--bg-input":       "#f5f0e8",
      "--border":         "#e0d8c8",
      "--text-primary":   "#2c2416",
      "--text-secondary": "#7a6a50",
      "--text-muted":     "#b0a080",
      "--accent":         "#8b5cf6",
      "--accent-hover":   "#7c3aed",
      "--accent-subtle":  "#f0eaff",
      "--bubble-out":     "#8b5cf6",
      "--bubble-out-text":"#fff",
      "--bubble-in":      "#ede8de",
      "--bubble-in-text": "#2c2416",
      "--online":         "#22c55e",
      "--scrollbar":      "#d0c8b0",
    },
  },
  {
    id: "arctic",
    name: "Arctic",
    category: "light",
    preview: ["#eaf4fb", "#ffffff", "#0369a1"],
    vars: {
      "--bg-base":        "#eaf4fb",
      "--bg-surface":     "#ffffff",
      "--bg-elevated":    "#f0f8ff",
      "--bg-input":       "#e0eef8",
      "--border":         "#bbd8f0",
      "--text-primary":   "#0c2d4a",
      "--text-secondary": "#4a7a9b",
      "--text-muted":     "#8ab4cc",
      "--accent":         "#0369a1",
      "--accent-hover":   "#025a8e",
      "--accent-subtle":  "#e0f0ff",
      "--bubble-out":     "#0369a1",
      "--bubble-out-text":"#fff",
      "--bubble-in":      "#deedf8",
      "--bubble-in-text": "#0c2d4a",
      "--online":         "#0ea5e9",
      "--scrollbar":      "#bbd8f0",
    },
  },
  {
    id: "warm-ivory",
    name: "Warm Ivory",
    category: "light",
    preview: ["#fdf6ec", "#fff9f0", "#d97706"],
    vars: {
      "--bg-base":        "#fdf6ec",
      "--bg-surface":     "#fff9f0",
      "--bg-elevated":    "#fffbf5",
      "--bg-input":       "#f5ede0",
      "--border":         "#e8d8c0",
      "--text-primary":   "#3d2c1a",
      "--text-secondary": "#8a6a40",
      "--text-muted":     "#c0a080",
      "--accent":         "#d97706",
      "--accent-hover":   "#b45309",
      "--accent-subtle":  "#fff7e6",
      "--bubble-out":     "#d97706",
      "--bubble-out-text":"#fff",
      "--bubble-in":      "#f0e4d0",
      "--bubble-in-text": "#3d2c1a",
      "--online":         "#22c55e",
      "--scrollbar":      "#dcc8a8",
    },
  },

  // ─── NEON / CYBERPUNK ──────────────────────────────────────────
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    category: "neon",
    preview: ["#0a0015", "#10002b", "#f000b8"],
    vars: {
      "--bg-base":        "#0a0015",
      "--bg-surface":     "#10002b",
      "--bg-elevated":    "#1a0035",
      "--bg-input":       "#07001a",
      "--border":         "#f000b840",
      "--text-primary":   "#f0e0ff",
      "--text-secondary": "#c060ff",
      "--text-muted":     "#602080",
      "--accent":         "#f000b8",
      "--accent-hover":   "#cc00a0",
      "--accent-subtle":  "#30003a",
      "--bubble-out":     "#f000b8",
      "--bubble-out-text":"#fff",
      "--bubble-in":      "#1e0040",
      "--bubble-in-text": "#f0e0ff",
      "--online":         "#00ff9f",
      "--scrollbar":      "#3a0060",
    },
  },
  {
    id: "neon-tokyo",
    name: "Neon Tokyo",
    category: "neon",
    preview: ["#050510", "#0a0a1f", "#ff2d78"],
    vars: {
      "--bg-base":        "#050510",
      "--bg-surface":     "#0a0a1f",
      "--bg-elevated":    "#10102a",
      "--bg-input":       "#05050f",
      "--border":         "#ff2d7830",
      "--text-primary":   "#ffe0f0",
      "--text-secondary": "#ff6aa0",
      "--text-muted":     "#601840",
      "--accent":         "#ff2d78",
      "--accent-hover":   "#ff005a",
      "--accent-subtle":  "#300020",
      "--bubble-out":     "#ff2d78",
      "--bubble-out-text":"#fff",
      "--bubble-in":      "#18082a",
      "--bubble-in-text": "#ffe0f0",
      "--online":         "#00f5c8",
      "--scrollbar":      "#2a0830",
    },
  },
  {
    id: "matrix",
    name: "Matrix",
    category: "neon",
    preview: ["#000500", "#001200", "#00ff41"],
    vars: {
      "--bg-base":        "#000500",
      "--bg-surface":     "#001200",
      "--bg-elevated":    "#001a00",
      "--bg-input":       "#000800",
      "--border":         "#00ff4120",
      "--text-primary":   "#00ff41",
      "--text-secondary": "#00aa2b",
      "--text-muted":     "#004a10",
      "--accent":         "#00ff41",
      "--accent-hover":   "#00dd38",
      "--accent-subtle":  "#001a08",
      "--bubble-out":     "#00aa2b",
      "--bubble-out-text":"#000500",
      "--bubble-in":      "#001800",
      "--bubble-in-text": "#00ff41",
      "--online":         "#00ff41",
      "--scrollbar":      "#003010",
    },
  },
  {
    id: "synthwave",
    name: "Synthwave",
    category: "neon",
    preview: ["#0e0020", "#180030", "#ff79c6"],
    vars: {
      "--bg-base":        "#0e0020",
      "--bg-surface":     "#180030",
      "--bg-elevated":    "#200040",
      "--bg-input":       "#0a0018",
      "--border":         "#ff79c630",
      "--text-primary":   "#f8f8f2",
      "--text-secondary": "#bd93f9",
      "--text-muted":     "#6272a4",
      "--accent":         "#ff79c6",
      "--accent-hover":   "#ff52b3",
      "--accent-subtle":  "#2d1040",
      "--bubble-out":     "#bd93f9",
      "--bubble-out-text":"#fff",
      "--bubble-in":      "#22103a",
      "--bubble-in-text": "#f8f8f2",
      "--online":         "#50fa7b",
      "--scrollbar":      "#3a1060",
    },
  },
  {
    id: "electric-blue",
    name: "Electric Blue",
    category: "neon",
    preview: ["#000814", "#001428", "#00b4d8"],
    vars: {
      "--bg-base":        "#000814",
      "--bg-surface":     "#001428",
      "--bg-elevated":    "#001e38",
      "--bg-input":       "#00080f",
      "--border":         "#00b4d830",
      "--text-primary":   "#caf0f8",
      "--text-secondary": "#0096c7",
      "--text-muted":     "#023e8a",
      "--accent":         "#00b4d8",
      "--accent-hover":   "#0096c7",
      "--accent-subtle":  "#001a30",
      "--bubble-out":     "#0096c7",
      "--bubble-out-text":"#fff",
      "--bubble-in":      "#001e35",
      "--bubble-in-text": "#caf0f8",
      "--online":         "#48cae4",
      "--scrollbar":      "#023e8a",
    },
  },

  // ─── RETRO ─────────────────────────────────────────────────────
  {
    id: "retro-terminal",
    name: "Terminal",
    category: "retro",
    preview: ["#0d0d0d", "#1a1a1a", "#33ff33"],
    vars: {
      "--bg-base":        "#0d0d0d",
      "--bg-surface":     "#1a1a1a",
      "--bg-elevated":    "#222222",
      "--bg-input":       "#111111",
      "--border":         "#33ff3330",
      "--text-primary":   "#33ff33",
      "--text-secondary": "#22aa22",
      "--text-muted":     "#114411",
      "--accent":         "#33ff33",
      "--accent-hover":   "#22cc22",
      "--accent-subtle":  "#0a1f0a",
      "--bubble-out":     "#22aa22",
      "--bubble-out-text":"#0d0d0d",
      "--bubble-in":      "#1e1e1e",
      "--bubble-in-text": "#33ff33",
      "--online":         "#33ff33",
      "--scrollbar":      "#222222",
    },
  },
  {
    id: "amber-crt",
    name: "Amber CRT",
    category: "retro",
    preview: ["#0f0900", "#1a1000", "#ffb300"],
    vars: {
      "--bg-base":        "#0f0900",
      "--bg-surface":     "#1a1000",
      "--bg-elevated":    "#221500",
      "--bg-input":       "#0a0700",
      "--border":         "#ffb30030",
      "--text-primary":   "#ffb300",
      "--text-secondary": "#cc8800",
      "--text-muted":     "#553300",
      "--accent":         "#ffb300",
      "--accent-hover":   "#ff9900",
      "--accent-subtle":  "#1f1000",
      "--bubble-out":     "#cc8800",
      "--bubble-out-text":"#0f0900",
      "--bubble-in":      "#1e1200",
      "--bubble-in-text": "#ffb300",
      "--online":         "#ffcc00",
      "--scrollbar":      "#2a1800",
    },
  },
  {
    id: "vaporwave",
    name: "Vaporwave",
    category: "retro",
    preview: ["#1a0533", "#2d0a55", "#ff71ce"],
    vars: {
      "--bg-base":        "#1a0533",
      "--bg-surface":     "#2d0a55",
      "--bg-elevated":    "#3d1068",
      "--bg-input":       "#150328",
      "--border":         "#ff71ce40",
      "--text-primary":   "#fff0ff",
      "--text-secondary": "#b967ff",
      "--text-muted":     "#5a2080",
      "--accent":         "#ff71ce",
      "--accent-hover":   "#ff50b8",
      "--accent-subtle":  "#2d0a44",
      "--bubble-out":     "#01cdfe",
      "--bubble-out-text":"#1a0533",
      "--bubble-in":      "#3a1060",
      "--bubble-in-text": "#fff0ff",
      "--online":         "#05ffa1",
      "--scrollbar":      "#4a1580",
    },
  },
  {
    id: "win95",
    name: "Win95",
    category: "retro",
    preview: ["#c0c0c0", "#008080", "#000080"],
    vars: {
      "--bg-base":        "#008080",
      "--bg-surface":     "#c0c0c0",
      "--bg-elevated":    "#d4d0c8",
      "--bg-input":       "#ffffff",
      "--border":         "#808080",
      "--text-primary":   "#000000",
      "--text-secondary": "#404040",
      "--text-muted":     "#808080",
      "--accent":         "#000080",
      "--accent-hover":   "#0000a0",
      "--accent-subtle":  "#d8d0e8",
      "--bubble-out":     "#000080",
      "--bubble-out-text":"#ffffff",
      "--bubble-in":      "#d4d0c8",
      "--bubble-in-text": "#000000",
      "--online":         "#00aa00",
      "--scrollbar":      "#a0a0a0",
    },
  },

  // ─── PASTEL ────────────────────────────────────────────────────
  {
    id: "cotton-candy",
    name: "Cotton Candy",
    category: "pastel",
    preview: ["#fce4ec", "#fff0f5", "#f48fb1"],
    vars: {
      "--bg-base":        "#fce4ec",
      "--bg-surface":     "#fff0f5",
      "--bg-elevated":    "#fff5f8",
      "--bg-input":       "#f8d7e3",
      "--border":         "#f0b8cc",
      "--text-primary":   "#4a1a2a",
      "--text-secondary": "#a0506a",
      "--text-muted":     "#d08090",
      "--accent":         "#f48fb1",
      "--accent-hover":   "#e91e8c",
      "--accent-subtle":  "#ffeef5",
      "--bubble-out":     "#f48fb1",
      "--bubble-out-text":"#fff",
      "--bubble-in":      "#fce4ec",
      "--bubble-in-text": "#4a1a2a",
      "--online":         "#80cbc4",
      "--scrollbar":      "#f0b8cc",
    },
  },
  {
    id: "mint-breeze",
    name: "Mint Breeze",
    category: "pastel",
    preview: ["#e8f5e9", "#f1fff2", "#81c784"],
    vars: {
      "--bg-base":        "#e8f5e9",
      "--bg-surface":     "#f1fff2",
      "--bg-elevated":    "#f5fff6",
      "--bg-input":       "#dff0e0",
      "--border":         "#b8ddb8",
      "--text-primary":   "#1b3a1e",
      "--text-secondary": "#4a7a4e",
      "--text-muted":     "#90b890",
      "--accent":         "#66bb6a",
      "--accent-hover":   "#4caf50",
      "--accent-subtle":  "#eefaee",
      "--bubble-out":     "#66bb6a",
      "--bubble-out-text":"#fff",
      "--bubble-in":      "#e0f2e0",
      "--bubble-in-text": "#1b3a1e",
      "--online":         "#26a69a",
      "--scrollbar":      "#b8ddb8",
    },
  },
  {
    id: "lavender-dream",
    name: "Lavender Dream",
    category: "pastel",
    preview: ["#ede7f6", "#f3eeff", "#ab47bc"],
    vars: {
      "--bg-base":        "#ede7f6",
      "--bg-surface":     "#f3eeff",
      "--bg-elevated":    "#f8f3ff",
      "--bg-input":       "#e0d8f0",
      "--border":         "#c8b8e0",
      "--text-primary":   "#2a1840",
      "--text-secondary": "#7a508a",
      "--text-muted":     "#b090c0",
      "--accent":         "#ab47bc",
      "--accent-hover":   "#9c27b0",
      "--accent-subtle":  "#f5f0ff",
      "--bubble-out":     "#ab47bc",
      "--bubble-out-text":"#fff",
      "--bubble-in":      "#e8e0f5",
      "--bubble-in-text": "#2a1840",
      "--online":         "#66bb6a",
      "--scrollbar":      "#c8b8e0",
    },
  },
  {
    id: "peach-fuzz",
    name: "Peach Fuzz",
    category: "pastel",
    preview: ["#fff3e0", "#fff8f0", "#ffa726"],
    vars: {
      "--bg-base":        "#fff3e0",
      "--bg-surface":     "#fff8f0",
      "--bg-elevated":    "#fffaf4",
      "--bg-input":       "#ffe8cc",
      "--border":         "#ffcc88",
      "--text-primary":   "#3e2000",
      "--text-secondary": "#8a5020",
      "--text-muted":     "#d09060",
      "--accent":         "#ffa726",
      "--accent-hover":   "#fb8c00",
      "--accent-subtle":  "#fff5e8",
      "--bubble-out":     "#ffa726",
      "--bubble-out-text":"#fff",
      "--bubble-in":      "#ffe8cc",
      "--bubble-in-text": "#3e2000",
      "--online":         "#66bb6a",
      "--scrollbar":      "#ffcc88",
    },
  },
  {
    id: "sky-bliss",
    name: "Sky Bliss",
    category: "pastel",
    preview: ["#e3f2fd", "#f0f8ff", "#42a5f5"],
    vars: {
      "--bg-base":        "#e3f2fd",
      "--bg-surface":     "#f0f8ff",
      "--bg-elevated":    "#f5fbff",
      "--bg-input":       "#d8edf8",
      "--border":         "#b0d4f0",
      "--text-primary":   "#0d2035",
      "--text-secondary": "#3a708a",
      "--text-muted":     "#80aac0",
      "--accent":         "#42a5f5",
      "--accent-hover":   "#1e88e5",
      "--accent-subtle":  "#eaf5ff",
      "--bubble-out":     "#42a5f5",
      "--bubble-out-text":"#fff",
      "--bubble-in":      "#daedf8",
      "--bubble-in-text": "#0d2035",
      "--online":         "#26c6da",
      "--scrollbar":      "#b0d4f0",
    },
  },

  // ─── COLORFUL / SPECIAL ────────────────────────────────────────
  {
    id: "sunset",
    name: "Sunset",
    category: "colorful",
    preview: ["#1a0a2e", "#2d1f0a", "#ff6b35"],
    vars: {
      "--bg-base":        "#1a0a1e",
      "--bg-surface":     "#2a1030",
      "--bg-elevated":    "#351540",
      "--bg-input":       "#150818",
      "--border":         "#5a2050",
      "--text-primary":   "#ffe5d0",
      "--text-secondary": "#ff9a6c",
      "--text-muted":     "#8a4050",
      "--accent":         "#ff6b35",
      "--accent-hover":   "#ff5520",
      "--accent-subtle":  "#3a1020",
      "--bubble-out":     "#ff6b35",
      "--bubble-out-text":"#fff",
      "--bubble-in":      "#3a1535",
      "--bubble-in-text": "#ffe5d0",
      "--online":         "#ffd93d",
      "--scrollbar":      "#5a2050",
    },
  },
  {
    id: "aurora",
    name: "Aurora",
    category: "colorful",
    preview: ["#050f14", "#0a1f28", "#00ffc8"],
    vars: {
      "--bg-base":        "#050f14",
      "--bg-surface":     "#0a1f28",
      "--bg-elevated":    "#102a38",
      "--bg-input":       "#05101a",
      "--border":         "#00ffc820",
      "--text-primary":   "#d0fff5",
      "--text-secondary": "#00c8a0",
      "--text-muted":     "#205050",
      "--accent":         "#00ffc8",
      "--accent-hover":   "#00e0b0",
      "--accent-subtle":  "#082a25",
      "--bubble-out":     "#00c8a0",
      "--bubble-out-text":"#050f14",
      "--bubble-in":      "#102832",
      "--bubble-in-text": "#d0fff5",
      "--online":         "#7fff7f",
      "--scrollbar":      "#205050",
    },
  },
  {
    id: "rose-gold",
    name: "Rose Gold",
    category: "colorful",
    preview: ["#1a0f10", "#2e1518", "#f4a5ae"],
    vars: {
      "--bg-base":        "#1a0f10",
      "--bg-surface":     "#2e1518",
      "--bg-elevated":    "#3e1c20",
      "--bg-input":       "#150c0d",
      "--border":         "#5a2530",
      "--text-primary":   "#fff0f0",
      "--text-secondary": "#d07080",
      "--text-muted":     "#803040",
      "--accent":         "#f4a5ae",
      "--accent-hover":   "#e88898",
      "--accent-subtle":  "#3a1520",
      "--bubble-out":     "#e88898",
      "--bubble-out-text":"#fff",
      "--bubble-in":      "#3a1822",
      "--bubble-in-text": "#fff0f0",
      "--online":         "#f4a5ae",
      "--scrollbar":      "#5a2530",
    },
  },
  {
    id: "nord",
    name: "Nord",
    category: "colorful",
    preview: ["#2e3440", "#3b4252", "#88c0d0"],
    vars: {
      "--bg-base":        "#2e3440",
      "--bg-surface":     "#3b4252",
      "--bg-elevated":    "#434c5e",
      "--bg-input":       "#292e39",
      "--border":         "#4c566a",
      "--text-primary":   "#eceff4",
      "--text-secondary": "#d8dee9",
      "--text-muted":     "#4c566a",
      "--accent":         "#88c0d0",
      "--accent-hover":   "#81a1c1",
      "--accent-subtle":  "#3b4a5a",
      "--bubble-out":     "#5e81ac",
      "--bubble-out-text":"#eceff4",
      "--bubble-in":      "#434c5e",
      "--bubble-in-text": "#eceff4",
      "--online":         "#a3be8c",
      "--scrollbar":      "#4c566a",
    },
  },
  {
    id: "solarized",
    name: "Solarized",
    category: "colorful",
    preview: ["#002b36", "#073642", "#2aa198"],
    vars: {
      "--bg-base":        "#002b36",
      "--bg-surface":     "#073642",
      "--bg-elevated":    "#0a3f4e",
      "--bg-input":       "#00222d",
      "--border":         "#1a4a57",
      "--text-primary":   "#839496",
      "--text-secondary": "#657b83",
      "--text-muted":     "#586e75",
      "--accent":         "#2aa198",
      "--accent-hover":   "#239990",
      "--accent-subtle":  "#073540",
      "--bubble-out":     "#268bd2",
      "--bubble-out-text":"#fdf6e3",
      "--bubble-in":      "#0a3f4e",
      "--bubble-in-text": "#839496",
      "--online":         "#859900",
      "--scrollbar":      "#1a4a57",
    },
  },
];

export const themeCategories = [
  { id: "all",      label: "All" },
  { id: "dark",     label: "Dark" },
  { id: "light",    label: "Light" },
  { id: "neon",     label: "Neon" },
  { id: "retro",    label: "Retro" },
  { id: "pastel",   label: "Pastel" },
  { id: "colorful", label: "Colorful" },
];